language: cpp

compiler:
  - clang
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install valgrind

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
  - mkdir Debug
  - cd Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make VERBOSE=1
  - ./protoson
  - valgrind --error-exitcode=1 --leak-check=full ./protoson

after_success:
  - coveralls --exclude test/catch.hpp --exclude test/unit.cpp --include src/pson.h src/pson_encoder.hpp src/pson_decoder.hpp --gcov-options '\-lp' --gcov 'gcov-4.9'