language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install valgrind

script:
  - make
  - ./protoson
  - valgrind --error-exitcode=1 --leak-check=full ./protoson

after_success:
  - coveralls --exclude test/catch.hpp --exclude test/unit.cpp --include src/pson.h src/pson_encoder.hpp src/pson_decoder.hpp --gcov-options '\-lp' --gcov 'gcov-4.9'