language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo pip install cpp-coveralls pyyaml
  - sudo apt-get install valgrind

script:
  - mkdir Debug
  - cd Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ./protoson
  - valgrind --error-exitcode=1 --leak-check=full ./protoson

after_success:
  - coveralls --exclude test/catch.hpp --exclude test/unit.cpp --include src/pson.h src/pson_encoder.hpp src/pson_decoder.hpp --gcov-options '\-lp' --gcov 'gcov-4.9'